// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrpTqyLmoiavXoF_7xQnfmE8hS-snRH-M',
    appId: '1:1070075590447:android:c81b84507ee76fa3dd53da',
    messagingSenderId: '1070075590447',
    projectId: 'we-chat-454aa',
    storageBucket: 'we-chat-454aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVoOdicNNDGnVQ8MWcOZZSJoqibnT02uA',
    appId: '1:1070075590447:ios:6f01aee7596188c6dd53da',
    messagingSenderId: '1070075590447',
    projectId: 'we-chat-454aa',
    storageBucket: 'we-chat-454aa.appspot.com',
    androidClientId: '1070075590447-e9q3n7ukk09ae6k8ftpup7ni42lv7bie.apps.googleusercontent.com',
    iosClientId: '1070075590447-lceh0vto3lpcofjf2ikkosc72jf7761b.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

}